#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# History Options
#

export HIST_EXPIRE_DUPS_FIRST=true
export HIST_IGNORE_ALL_DUPS=true
export HIST_FIND_NO_DUPS=true

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

export XDG_CONFIG_HOME="$HOME/.config"

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  $XDG_CONFIG_HOME/yarn/global/node_modules/.bin
  /opt/homebrew/{bin,sbin}
  /usr/{bin,sbin}
  /{bin,sbin}
  $path
)

export LIBRARY_PATH="$LIBRARY_PATH:/opt/homebrew/lib"

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-g -i -F -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Use Secret Agent (TouchID) for SSH
export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

eval "$(rtx activate zsh)"
