#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Aliases
#

# alias ls=eza
alias ls=lsd
alias cat=bat
alias docker=podman
alias pdm=podman
alias vi=nvim
alias vim=nvim
alias brewi='brew info'
alias lg=lazygit
alias lgd='lazygit --git-dir=$HOME/.dotfiles --work-tree=$HOME'

#
# Mix (Elixir) aliases
#

alias mc='mix compile'
alias mcf='mix compile --force'
alias mcl='mix clean'
alias mcr='mix credo'
alias mdc='mix deps.compile'
alias mdg='mix deps.get'
alias mdu='mix deps.unlock'
alias mdx='mix deps.clean'
alias mdo='mix do'
alias mdun='mix deps.unlock'
alias mdup='mix deps.update'
alias mev='mix eval'
alias mem='mix ecto.migrate'
alias mer='mix ecto.rollback'
alias mf='mix format'
alias ml='mix local'
alias mlh='mix local.hex'
alias mlr='mix local.rebar'
alias mn='mix new'
alias mpre='mix precommit'
alias mprt='mix phx.routes'
alias mps='mix phx.server'
alias mr='mix run'
alias mre='mix reset'
alias ms='mix setup'
alias msi='iex -S mix'
alias mt='mix test'

#
# Extra Git aliases
#

alias gst=gwS
alias ga=gia
alias gaa=giu
alias gis='git restore --staged'
alias gpo='git push origin $(git branch --show-current)'
alias gpou='git push -u origin $(git branch --show-current)'
alias gpfo='git push --force-with-lease origin $(git branch --show-current)'
alias gwa='git worktree add'
alias gwl='git worktree list'
alias gwr='git worktree remove'

alias tig='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

#
# JJ aliases
#

alias lj='lazyjj'

alias ja='jj abandon'
alias jab='jj absorb'

alias jb='jj bookmark'
alias jbc='jj bookmark create'
alias jbd='jj bookmark delete'
alias jbl='jj bookmark list'
alias jbm='jj bookmark move'
alias jbr='jj bookmark rename'
alias jbs='jj bookmark set'
alias jbt='jj bookmark track'
alias jbu='jj bookmark untrack'

alias jc='jj commit'
alias jcf='jj config'
alias jcfe='jj config edit'
alias jcfs='jj config set'
alias jd='jj describe'
alias jdf='jj diff'
alias jdfe='jj diffedit'
alias je='jj edit'
alias jf='jj fix'
alias jgf='jj git fetch'
alias jgp='jj git push'
alias jgpn='jj git push --allow-new'
alias jl='jj log'
alias jn='jj new'
alias jnn='jj new --no-edit'
alias jr='jj rebase'
alias jre='jj redo'
alias jrv='jj resolve'
alias jrs='jj restore'
alias js='jj show'
alias jst='jj status'
alias jsq='jj squash'
alias ju='jj undo'


eval "$(starship init zsh)"

eval "$(thefuck --alias)"

export FZF_DEFAULT_OPTS="--style=full"
source <(fzf --zsh)

eval "$(zoxide init zsh --cmd cd)"

eval "$(mise activate zsh)"
