#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Erlang Options
#

export ERL_AFLAGS="-kernel shell_history enabled"
export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"
export KERL_DOC_TARGETS=chunks
export KERL_BUILD_DOCS=yes

#
# Elixir Options
#

local cores=$(sysctl -n hw.ncpu)
export MIX_OS_DEPS_COMPILE_PARTITION_COUNT=$(expr $cores / 2)


test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#
# Aliases
#
# alias ls=eza
alias ls=lsd
alias cat=bat
alias docker=podman
alias pdm=podman
alias vi=nvim
alias vim=nvim
alias brewi='brew info'
alias lg=lazygit
alias lgd='lazygit --git-dir=$HOME/.dotfiles --work-tree=$HOME'
alias mt='mix test'
alias mf='mix format'
alias mdg='mix deps.get'

#
# Extra Git aliases
#
alias gst=gwS
alias ga=gia
alias gaa=giu
alias gis='git restore --staged'
alias gpo='git push origin $(git branch --show-current)'
alias gpou='git push -u origin $(git branch --show-current)'
alias gpfo='git push --force-with-lease origin $(git branch --show-current)'
alias gwa='git worktree add'
alias gwl='git worktree list'
alias gwr='git worktree remove'
alias tig='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'

#
# JJ aliases
#
alias lj='lazyjj'
alias ja='jj absorb'
alias jbc='jj bookmark create'
alias jc='jj commit'
alias jcf='jj config'
alias jce='jj config edit'
alias jcs='jj config set'
alias jd='jj describe'
alias jde='jj diffedit'
alias jdf='jj diff'
alias je='jj edit'
alias jf='jj fix'
alias jgf='jj git fetch'
alias jgn='jj git push --allow-new'
alias jgp='jj git push'
alias jl='jj log'
alias jn='jj new'
alias jr='jj rebase'
alias jre='jj redo'
alias jrv='jj resolve'
alias jrs='jj restore'
alias js='jj show'
alias jst='jj status'
alias jsq='jj squash'
alias ju='jj undo'


eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/quick-term.omp.json)"

eval "$(thefuck --alias)"

export FZF_DEFAULT_OPTS="--style=full"
source <(fzf --zsh)

eval "$(zoxide init zsh --cmd cd)"

# Use Secret Agent (TouchID) for SSH
export SSH_AUTH_SOCK=$HOME/Library/Containers/com.maxgoedjen.Secretive.SecretAgent/Data/socket.ssh

eval "$(mise activate zsh)"
