#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

#
# Erlang Options
#

export ERL_AFLAGS="-kernel shell_history enabled"
export KERL_CONFIGURE_OPTIONS="--disable-debug --without-javac"
export KERL_DOC_TARGETS=chunks
export KERL_BUILD_DOCS=yes

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"

#
# Additional Aliases
#
alias ls=eza
alias gst=gwS
alias ga=gia
alias gaa=giu
alias gis='git restore --staged'
alias gpo='git push origin $(git branch --show-current)'
alias gpou='git push -u origin $(git branch --show-current)'
alias gpfo='git push --force-with-lease origin $(git branch --show-current)'
alias gwa='git worktree add'
alias gwl='git worktree list'
alias gwr='git worktree remove'
alias tig='git --git-dir=$HOME/.dotfiles/ --work-tree=$HOME'
alias vi=nvim
alias vim=nvim
alias brewi='brew info'
alias lg=lazygit
alias lgd='lazygit --git-dir=$HOME/.dotfiles --work-tree=$HOME'
alias mt='mix test'
alias mdg='mix deps.get'


eval "$(oh-my-posh init zsh --config $(brew --prefix oh-my-posh)/themes/quick-term.omp.json)"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
eval "$(zoxide init --cmd cd zsh)"
